### ISSUE TITLE
Homey crash when enabling V2.0 beta

### ISSUE THREAD

**Issue by Asinke** [gruijter/com.gruijter.insights2csv#1] opened 2018-11-12 07:08 UTC
Hi Robin, While testing your app I noticed homey crashes (tested twice, crashed twice). 
How can I help you providing required information?

**Comment by gruijter** [comment] 2018-11-12 07:29
This is caused by a bug in Homey Insights itself. It is a long lasting bug, and we can only hope Athom has it fixed in v2.

**Comment by gruijter** [comment] 2019-03-23 14:32
I'm rewriting the app to be compatible with Homey V2. The insights handling has been significantly changed.

**Closed as completed by gruijter** 2019-03-23 14:32 UTC
