### ISSUE TITLE
TypeError: Cannot read property ‘replace’ of undefined at Promise (/app.js:532:44) at at process._tickCallback (internal/process/next_tick.js:89.7)

### ISSUE THREAD

**Issue by PMekerle** [gruijter/com.gruijter.insights2csv#7] opened 2019-10-05 09:49 UTC
Here are more details about the error I'm getting:

![1](https://user-images.githubusercontent.com/56190592/66253278-e8811e80-e765-11e9-9041-0c8bfaaba2fd.png)
![2](https://user-images.githubusercontent.com/56190592/66253279-e919b500-e765-11e9-92d3-891b01d08108.png)
![3](https://user-images.githubusercontent.com/56190592/66253280-e919b500-e765-11e9-85ba-326a6cc6f240.png)
![4](https://user-images.githubusercontent.com/56190592/66253281-e919b500-e765-11e9-84a4-1c19d471ac9f.png)

Thx in advance for taking a look. And for making this app of course! :)

**Comment by gruijter** [comment] 2019-10-06 10:14
Thx for the detailed issue report. I'm investigating right now (its raining anyway :) )

**Comment by gruijter** [comment] 2019-10-06 10:33
I cannot reproduce the problem. Did you try uninstalling the app, and installing/configuring it again?

I did find a problem though with showing the set folder in settings. There could be a folder setup, even when it is not showing it. This will be fixed in the next release.

**Comment by gruijter** [comment] 2019-10-06 18:14
please try v2.5.0 and reopen the issue if the problem persists.

**Comment by PMekerle** [comment] 2019-10-09 13:04
Hi

Thx for the new version.
I'm getting another error now. Also I reinstalled, but still not working.
I tested the NAS settings, it works fine and he writes the test file perfectly.
But then when running the export I get these logs:

NAS	WebDAV	FTP	Logs
Delete
2019-10-09 14:59:48 [log] [App] Exporting all insights yesterday
2019-10-09 14:59:46 [err] [App] { Error: STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights. at SMB2Forge.request (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:22:15) at module.exports.exists (/node_modules/@marsaud/smb2/lib/api/exists.js:18:3) at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:52:21 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:147:8 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:116:25 at Object. (/node_modules/@marsaud/smb2/lib/tools/message.js:15:15) at Socket. (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:71:31) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) messageName: 'open', params: { path: '20191009T125841Z\\' }, message: 'STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights.', code: 'STATUS_ACCESS_DENIED' }
2019-10-09 14:59:46 [log] [App] 9 files zipped, 21428 total bytes
2019-10-09 14:59:44 [log] [App] getting logs related to nl.philips.hue
2019-10-09 14:59:36 [log] [App] Connection successfull!
2019-10-09 14:59:36 [log] [App] testing SMB settings from frontend
2019-10-09 14:59:34 [err] [App] { Error: STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights. at SMB2Forge.request (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:22:15) at module.exports.exists (/node_modules/@marsaud/smb2/lib/api/exists.js:18:3) at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:52:21 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:147:8 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:116:25 at Object. (/node_modules/@marsaud/smb2/lib/tools/message.js:15:15) at Socket. (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:71:31) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) messageName: 'open', params: { path: '20191009T125841Z\\' }, message: 'STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights.', code: 'STATUS_ACCESS_DENIED' }
2019-10-09 14:59:34 [log] [App] 3 files zipped, 3923 total bytes
2019-10-09 14:59:33 [log] [App] getting logs related to io.nuki
2019-10-09 14:59:23 [err] [App] { Error: STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights. at SMB2Forge.request (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:22:15) at module.exports.exists (/node_modules/@marsaud/smb2/lib/api/exists.js:18:3) at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:52:21 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:147:8 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:116:25 at Object. (/node_modules/@marsaud/smb2/lib/tools/message.js:15:15) at Socket. (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:71:31) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) messageName: 'open', params: { path: '20191009T125841Z\\' }, message: 'STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights.', code: 'STATUS_ACCESS_DENIED' }
2019-10-09 14:59:23 [log] [App] 0 files zipped, 22 total bytes
2019-10-09 14:59:23 [log] [App] getting logs related to com.athom.homeyscript
2019-10-09 14:59:13 [err] [App] { Error: STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights. at SMB2Forge.request (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:22:15) at module.exports.exists (/node_modules/@marsaud/smb2/lib/api/exists.js:18:3) at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:52:21 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:147:8 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:116:25 at Object. (/node_modules/@marsaud/smb2/lib/tools/message.js:15:15) at Socket. (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:71:31) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) messageName: 'open', params: { path: '20191009T125841Z\\' }, message: 'STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights.', code: 'STATUS_ACCESS_DENIED' }
2019-10-09 14:59:13 [log] [App] 0 files zipped, 22 total bytes
2019-10-09 14:59:13 [log] [App] getting logs related to nl.hdg.battery
2019-10-09 14:59:03 [err] [App] { Error: STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights. at SMB2Forge.request (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:22:15) at module.exports.exists (/node_modules/@marsaud/smb2/lib/api/exists.js:18:3) at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:52:21 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:147:8 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:116:25 at Object. (/node_modules/@marsaud/smb2/lib/tools/message.js:15:15) at Socket. (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:71:31) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) messageName: 'open', params: { path: '20191009T125841Z\\' }, message: 'STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights.', code: 'STATUS_ACCESS_DENIED' }
2019-10-09 14:59:03 [log] [App] 0 files zipped, 22 total bytes
2019-10-09 14:59:03 [log] [App] getting logs related to openmindnl.ledcollection
2019-10-09 14:58:53 [err] [App] { Error: STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights. at SMB2Forge.request (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:22:15) at module.exports.exists (/node_modules/@marsaud/smb2/lib/api/exists.js:18:3) at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:52:21 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:147:8 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:116:25 at Object. (/node_modules/@marsaud/smb2/lib/tools/message.js:15:15) at Socket. (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:71:31) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) messageName: 'open', params: { path: '20191009T125841Z\\' }, message: 'STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights.', code: 'STATUS_ACCESS_DENIED' }
2019-10-09 14:58:52 [log] [App] 0 files zipped, 22 total bytes
2019-10-09 14:58:52 [log] [App] getting logs related to nl.terryhendrix.smartpresence
2019-10-09 14:58:42 [err] [App] { Error: STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights. at SMB2Forge.request (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:22:15) at module.exports.exists (/node_modules/@marsaud/smb2/lib/api/exists.js:18:3) at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:52:21 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:147:8 at /node_modules/@marsaud/smb2/lib/tools/smb2-connection.js:116:25 at Object. (/node_modules/@marsaud/smb2/lib/tools/message.js:15:15) at Socket. (/node_modules/@marsaud/smb2/lib/tools/smb2-forge.js:71:31) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) messageName: 'open', params: { path: '20191009T125841Z\\' }, message: 'STATUS_ACCESS_DENIED (0xC0000022) : {Access Denied} A process has requested access to an object but has not been granted those access rights.', code: 'STATUS_ACCESS_DENIED' }
2019-10-09 14:58:42 [log] [App] 6 files zipped, 9456 total bytes
2019-10-09 14:58:41 [log] [App] getting logs related to eu.elro.flamingo
2019-10-09 14:58:41 [log] [App] Exporting all insights yesterday
2019-10-09 14:58:23 [log] [App] STATUS_BAD_NETWORK_NAME (0xC00000CC) : {Network Name Not Found} The specified share name cannot be found on the remote server.
2019-10-09 14:58:23 [log] [App] testing SMB settings from frontend
2019-10-09 14:58:17 [log] [App] smbSettings changed from frontend
2019-10-09 14:58:13 [log] [App] Connection successfull!
2019-10-09 14:58:13 [log] [App] testing SMB settings from frontend
2019-10-09 14:57:58 [log] [App] Connection successfull!
2019-10-09 14:57:58 [log] [App] testing SMB settings from frontend
2019-10-09 14:57:48 [log] [App] Connection successfull!
2019-10-09 14:57:48 [log] [App] testing SMB settings from frontend

**Comment by gruijter** [comment] 2020-03-07 19:40
New version 2.5.1 available with some fixes.

https://homey.app/a/com.gruijter.insights2csv/test/

Can you check and let me know if this fixes it for you?

**Closed as completed** 2022-03-16 17:56 UTC
Labels: bug
